config/routes.rb
Rails.application.routes.draw do
  resources :images

  get 'useradministration/show'

  get 'useradministration/edit'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  mount Ckeditor::Engine => '/ckeditor'
  get 'frontend/show'

  get 'frontend/index'

  get "frontend" => 'frontend#index'

  mount Rich::Engine => '/rich', :as => 'rich'
  devise_for :views
  devise_for :models
  devise_for :users, controllers: { sessions: "users/sessions" }
  resources :locations
  resources :useradministration do
    get :add
    get :remove
  end
  resources :typs
  resources :menus do
    get :up
    get :down
  end

  resources :contentperpages

  resources :contents

  resources :sites
  get '/frontend/:id', to: 'frontend#show'
  get '/frontend:menu', to: 'frontend#show'
  get '/menus/:id/up', to: 'menus#up'
  get '/menus/:id/down', to: 'menus#down'
  get "/" , to: 'frontend#index'
  get "/useradministration/add/:user_id&:role_id", to:'useradministration#add'
  get "/useradministration/remove/:user_id&:role_id", to:'useradministration#remove'
  get '/frontend/bild', to: 'frontend#image'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :contentperpage
  validates :text ,:presence => true
  # Paperclip
  has_attached_file :pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :pic, :content_type => /^image\/(png|gif|jpeg)/, :message => 'only (png/gif/jpeg) images'

end

app/models/contentperpage.rb
class Contentperpage < ActiveRecord::Base
  has_many :contents
  has_many :menus
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :file, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :file, :content_type => /^image\/(png|gif|jpeg)/, :message => 'only (png/gif/jpeg) images'
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :menu
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :contentperpage
  belongs_to :sites
  belongs_to :location
  belongs_to :typ
  validates :name ,  :presence => true
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :menus

end

app/models/typ.rb
class Typ < ActiveRecord::Base
  has_many :menu
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :assign_default_role

  def assign_default_role
        add_role(:user)
  end

end

app/models/users_roles.rb
class Users_Roles < ActiveRecord::Base
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/contents_controller.rb
class ContentsController < LayoutadminController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  # Paperclip

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:text,:id,:pic, :useronly,:active)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/frondend_helper.rb
module FrondendHelper
end

app/helpers/frontend_helper.rb
module FrontendHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/typs_helper.rb
module TypsHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content, multipart: true) do |f| %>
        <% if @content.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@content.errors.count, "error") %> prohibited this location from being saved:</h2>

                  <ul>
                    <% @content.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
        <% end %>
        <div class="field">
          <%= f.bootsy_area :text%>
        </div>
   <div class="field">
  <%= f.label :pic %><br>
<%= f.file_field :pic%>
</div>
        <div class="field">
          <%= f.label :useronly %><br>
        <%= f.check_box :useronly %>
        </div>
        <div class="field">
          <%= f.label :active %><br>
          <%= f.check_box :active %>
        </div>
  <div class="actions">

        <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form' %>


<%= link_to image_tag('back.png', height: '20', width: '20'), contents_path %>

app/views/contents/index.html.erb
<% @contents.all.each do |content|
%>
          <table><tr  >

            <td width="200" ><%= content.text %></td>
            <td ><%= link_to image_tag('edit.png', height: '20', width: '20'), content %></td>

          </tr>
          </table>

<%end %>
<%= link_to image_tag('new.png', height: '20', width: '20'), new_content_path %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @content.text %>
</p>

<%= link_to image_tag('edit.png', height: '20', width: '20'), edit_content_path(@content) %> |
<%= link_to image_tag('back.png', height: '20', width: '20'), contents_path %>