config/routes.rb
Rails.application.routes.draw do
  resources :images

  get 'useradministration/show'

  get 'useradministration/edit'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  mount Ckeditor::Engine => '/ckeditor'
  get 'frontend/show'

  get 'frontend/index'

  get "frontend" => 'frontend#index'

  mount Rich::Engine => '/rich', :as => 'rich'
  devise_for :views
  devise_for :models
  devise_for :users, controllers: { sessions: "users/sessions" }
  resources :locations
  resources :useradministration do
    get :add
    get :remove
  end
  resources :typs
  resources :menus do
    get :up
    get :down
  end

  resources :contentperpages

  resources :contents

  resources :sites
  get '/frontend/:id', to: 'frontend#show'
  get '/frontend:menu', to: 'frontend#show'
  get '/menus/:id/up', to: 'menus#up'
  get '/menus/:id/down', to: 'menus#down'
  get "/" , to: 'frontend#index'
  get "/useradministration/add/:user_id&:role_id", to:'useradministration#add'
  get "/useradministration/remove/:user_id&:role_id", to:'useradministration#remove'
  get '/frontend/bild', to: 'frontend#image'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :contentperpage
  validates :text ,:presence => true
  # Paperclip
  has_attached_file :pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :pic, :content_type => /^image\/(png|gif|jpeg)/, :message => 'only (png/gif/jpeg) images'

end

app/models/contentperpage.rb
class Contentperpage < ActiveRecord::Base
  has_many :contents
  has_many :menus
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :file, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :file, :content_type => /^image\/(png|gif|jpeg)/, :message => 'only (png/gif/jpeg) images'
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :menu
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :contentperpage
  belongs_to :sites
  belongs_to :location
  belongs_to :typ
  validates :name ,  :presence => true
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :menus

end

app/models/typ.rb
class Typ < ActiveRecord::Base
  has_many :menu
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :assign_default_role

  def assign_default_role
        add_role(:user)
  end

end

app/models/users_roles.rb
class Users_Roles < ActiveRecord::Base
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/contentperpages_controller.rb
class ContentperpagesController < LayoutadminController
  before_action :set_contentperpage, only: [ :create_new,:show, :edit, :update, :destroy]
  before_action :set_id, only: [:index]
  before_action :set_infos, only: [:create_new,:new]

  respond_to :html, :json

  # GET /contentperpages
  # GET /contentperpages.json
  def index
    @contentperpages = Contentperpage.all
  end
  # GET /contentperpages/1
  # GET /contentperpages/1.json
  def show
  end

  # GET /contentperpages/new
  def new
    @contentperpage = Contentperpage.new
    @contentperpage.menu_id = @contentperpagemenuid
    @contentperpage.content_id = @contentperpagecontentid
  end

  # GET /contentperpages/1/edit
  def edit
  end
def changesite(uid)
  redirect_to @contentperpage
end

  def create_new(contentidget,menuid)
    @contentperpage=Contentperpage.new
    @contentperpage.menu_id =  menuid
    @contentperpage.content_id = contentidget


      if @contentperpage.save
        self.changesite(@contentperpage)
      else



      end

  end


  # POST /contentperpages
  # POST /contentperpages.json
  def create
    @contentperpage = Contentperpage.new(contentperpage_params)

    respond_to do |format|
      if @contentperpage.save
        format.html { redirect_to @contentperpage, notice: 'Contentperpage was successfully created.' }
        format.json { render :show, status: :created, location: @contentperpage }

      else
        format.html { render :new }
        format.json { render json: @contentperpage.errors, status: :unprocessable_entity }
      end
    end
    end

  # PATCH/PUT /contentperpages/1
  # PATCH/PUT /contentperpages/1.json
  def update
    respond_to do |format|
      if @contentperpage.save
        format.html { redirect_to @contentperpage, notice: 'Contentperpage was successfully created.' }
        format.json { render :show, status: :created, location: @contentperpage }
      else
        format.html { render :new }
        format.json { render json: @contentperpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contentperpages/1
  # DELETE /contentperpages/1.json
  def destroy
    @contentperpagemenuid = @contentperpage.menu_id
    @contentperpage.destroy
    redirect_to contentperpages_path(:menu =>@contentperpagemenuid)

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contentperpage
      @contentperpage = Contentperpage.find(params[:id])
      @contentperpagecontentid = params[:content]
      @contentperpagemenuid = params[:menu]
    end
    def set_id
      @contentperpagecontentid = params[:content]
    @contentperpagemenuid = params[:menu]
    @contentselectet = Contentperpage.where(menu_id:  @contentperpagemenuid)
    @contentobject= self.new
    if @contentselectet.nil?
      @contentnotelectet = Content.all
    else
      @contentnotelectet = Content.where('id not in (?)',@contentselectet.map(&:content_id))
    end
    end

    def set_infos
      @contentperpagemenuid = params[:menu]
      @contentobject= self.new
      @contentperpagecontentid = params[:content]
      @content=Content.find(@contentperpagecontentid)
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def contentperpage_params
      params.require(:contentperpage).permit(:content_id, :menu_id)
    end
end

app/helpers/contentperpages_helper.rb
module ContentperpagesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/frondend_helper.rb
module FrondendHelper
end

app/helpers/frontend_helper.rb
module FrontendHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/typs_helper.rb
module TypsHelper
end

app/views/contentperpages/_form.html.erb
<%= form_for(@contentperpage) do |f| %>
  <% if @contentperpage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contentperpage.errors.count, "error") %> prohibited this contentperpage from being saved:</h2>

      <ul>
      <% @contentperpage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content_id %><br>
    <%= f.number_field :content_id %>
  </div>
  <div class="field">
    <%= f.label :menu_id %><br>
    <%= f.number_field :menu_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contentperpages/edit.html.erb
<table> <tr>

  <td><%= Content.find(@contentperpage.content_id).text %></td></tr><td>

  <td>Verbundung trennen:<%= link_to image_tag('delete.png', height: '20', width: '20'), @contentperpage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</td>


  </tr>
</table>




<%= link_to image_tag('back.png', height: '20', width: '20'),  contentperpages_path(:menu => @contentperpage.menu_id) %>

app/views/contentperpages/index.html.erb
<p id="notice"><%= notice %></p>

<p ><b>verbunden:</b></p>
<% @contentselectet.all.each do |content|
%>
        <div >
          <table><tr>

            <td width="100"><%= Content.find(content.content_id).text %></td>
            <td><%= link_to image_tag('edit.png', height: '20', width: '20'), edit_contentperpage_path(:id => content, :menu => @contentperpagemenuid ) %></td>

          </tr>
          </table>
        </div>
<%end %>
<br>
<br>
<p ><b>nicht verbunden:</b></p>
<% @contentnotelectet.all.each do |content| %>
        <div ><table> <tr>

          <td width="100"><%= content.text %></td>
          <td><%= link_to image_tag('edit.png', height: '20', width: '20'), new_contentperpage_path(:menu => @contentperpagemenuid,:content => content)  %></td>


        </tr>
        </table>
        </div>
<%end%>


<%= link_to image_tag('back.png', height: '20', width: '20'), contentperpages_path %>

app/views/contentperpages/new.html.erb
        <div ><table> <tr>

            <td><%= @content.text %></td></tr><td>

          <%= form_for(@contentperpage) do |f| %>

                  <div class="field">

                    <%= f.hidden_field :content_id %>
                  </div>
                  <div class="field">

                    <%= f.hidden_field :menu_id %>
                  </div>
                  <div class="actions">
                    <%= f.submit %>
                  </div>
          <% end %>
        </td>


            </tr>
          </table>
        </div>



<%= link_to 'Back', contentperpages_path %>

app/views/contentperpages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contentid:</strong>
  <%= @contentperpage.content_id %>
</p>

<p>
  <strong>Subitemid:</strong>
  <%= @contentperpage.menu_id %>
</p>

<%= link_to 'Edit', edit_contentperpage_path(@contentperpage) %> |
<%= link_to 'Back',  contentperpages_path(:menu => @contentperpage.menu_id) %>