config/routes.rb
Rails.application.routes.draw do
  resources :images

  get 'useradministration/show'

  get 'useradministration/edit'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  mount Ckeditor::Engine => '/ckeditor'
  get 'frontend/show'

  get 'frontend/index'

  get "frontend" => 'frontend#index'

  mount Rich::Engine => '/rich', :as => 'rich'
  devise_for :views
  devise_for :models
  devise_for :users, controllers: { sessions: "users/sessions" }
  resources :locations
  resources :useradministration do
    get :add
    get :remove
  end
  resources :typs
  resources :menus do
    get :up
    get :down
  end

  resources :contentperpages

  resources :contents

  resources :sites
  get '/frontend/:id', to: 'frontend#show'
  get '/frontend:menu', to: 'frontend#show'
  get '/menus/:id/up', to: 'menus#up'
  get '/menus/:id/down', to: 'menus#down'
  get "/" , to: 'frontend#index'
  get "/useradministration/add/:user_id&:role_id", to:'useradministration#add'
  get "/useradministration/remove/:user_id&:role_id", to:'useradministration#remove'
  get '/frontend/bild', to: 'frontend#image'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :contentperpage
  validates :text ,:presence => true
  # Paperclip
  has_attached_file :pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :pic, :content_type => /^image\/(png|gif|jpeg)/, :message => 'only (png/gif/jpeg) images'

end

app/models/contentperpage.rb
class Contentperpage < ActiveRecord::Base
  has_many :contents
  has_many :menus
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :file, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :file, :content_type => /^image\/(png|gif|jpeg)/, :message => 'only (png/gif/jpeg) images'
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :menu
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :contentperpage
  belongs_to :sites
  belongs_to :location
  belongs_to :typ
  validates :name ,  :presence => true
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :menus

end

app/models/typ.rb
class Typ < ActiveRecord::Base
  has_many :menu
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :assign_default_role

  def assign_default_role
        add_role(:user)
  end

end

app/models/users_roles.rb
class Users_Roles < ActiveRecord::Base
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/sites_controller.rb
class SitesController < LayoutadminController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:impressum)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/frondend_helper.rb
module FrondendHelper
end

app/helpers/frontend_helper.rb
module FrontendHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/typs_helper.rb
module TypsHelper
end

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :impressum %><br>
    <%= f.text_area :impressum %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing Site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/example.html.erb
<div name="main" align="center"  style="width:1100px; height:600px; background-color:#999999; position: relative; alignment-adjust: central;" >
  <div name="hmenu" style="float:left; width:100%; height:100px; background-color:#CCFF66"></div>
  <div name="vmenu" style="float:left; width:100px; height:400px; background-color:#00F"></div>
  <div name="content" style="float:left; width:1000px; height:400px; background-color:#FF0"></div>
  <div name="content" style="float:left; width:1100px; height:100px; background-color:#6CC"></div>


</div>

app/views/sites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sites</h1>

<table>
  <thead>
    <tr>
      <th>Impressum</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= site.impressum %></td>
        <td><%= link_to 'Show', site %></td>
        <td><%= link_to 'Edit', edit_site_path(site) %></td>
        <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site', new_site_path %>

app/views/sites/new.html.erb
<h1>New Site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Impressum:</strong>
  <%= @site.impressum %>
</p>

<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>